env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  no-unused-vars:
    - error
    - varsIgnorePattern: '^_'
      argsIgnorePattern: '^_'
  camelcase: error
  indent:
    - error
    - "tab"
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always