apiVersion: v1
kind: Service
metadata:
  name: bm
  namespace: appveen
spec:
  type: ClusterIP
  selector:
    app: bm
  ports:
    - protocol: TCP
      name: http-port
      port: 80
      targetPort: 10011
    - protocol: TCP
      name: https-port
      port: 443
      targetPort: 10443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bm
  namespace: appveen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bm
  template:
    metadata:
      labels:
        app: bm
    spec:
      serviceAccountName: ds-admin
      containers:
        - name: bm
          image: 'appveen/datanimbus.io.bm:2.3.0'
          ports:
            - containerPort: 10011
            - containerPort: 10443
          livenessProbe:
            httpGet:
              path: /bm/internal/health/live
              port: 10011
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              path: /bm/internal/health/ready
              port: 10011
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 60
          envFrom:
          - configMapRef:
              name: config
